// Derived from world-countries 5.1.0 (ODbL-1.0).
// Source: https://github.com/mledoze/countries
// XK (Kosovo) is omitted because it is not an officially assigned ISO 3166-1 code.
const countryRecords = [
  ['KR', '대한민국', 'Republic of Korea', 'Republic of Korea', '한국', 'KOR'],
  ['AF', 'افغانستان', 'Afghanistan', 'Islamic Republic of Afghanistan', '아프가니스탄', 'AFG'],
  ['AX', 'Åland', 'Åland Islands', 'Åland Islands', '올란드 제도', 'ALA'],
  ['AL', 'Shqipëria', 'Albania', 'Republic of Albania', '알바니아', 'ALB'],
  ['DZ', 'الجزائر', 'Algeria', "People's Democratic Republic of Algeria", '알제리', 'DZA'],
  ['AS', 'Sāmoa Amelika', 'American Samoa', 'American Samoa', '아메리칸사모아', 'ASM'],
  ['AD', 'Andorra', 'Andorra', 'Principality of Andorra', '안도라', 'AND'],
  ['AO', 'Angola', 'Angola', 'Republic of Angola', '앙골라', 'AGO'],
  ['AI', 'Anguilla', 'Anguilla', 'Anguilla', '앵귈라', 'AIA'],
  ['AQ', 'Antarctica', 'Antarctica', 'Antarctica', '남극', 'ATA'],
  [
    'AG',
    'Antigua and Barbuda',
    'Antigua and Barbuda',
    'Antigua and Barbuda',
    '앤티가 바부다',
    'ATG',
  ],
  ['AR', 'Argentina', 'Argentina', 'Argentine Republic', '아르헨티나', 'ARG'],
  ['AM', 'Հայաստան', 'Armenia', 'Republic of Armenia', '아르메니아', 'ARM'],
  ['AW', 'Aruba', 'Aruba', 'Aruba', '아루바', 'ABW'],
  ['AU', 'Australia', 'Australia', 'Commonwealth of Australia', '호주', 'AUS'],
  ['AT', 'Österreich', 'Austria', 'Republic of Austria', '오스트리아', 'AUT'],
  ['AZ', 'Azərbaycan', 'Azerbaijan', 'Republic of Azerbaijan', '아제르바이잔', 'AZE'],
  ['BS', 'Bahamas', 'Bahamas', 'Commonwealth of the Bahamas', '바하마', 'BHS'],
  ['BH', 'البحرين', 'Bahrain', 'Kingdom of Bahrain', '바레인', 'BHR'],
  ['BD', 'বাংলাদেশ', 'Bangladesh', "People's Republic of Bangladesh", '방글라데시', 'BGD'],
  ['BB', 'Barbados', 'Barbados', 'Barbados', '바베이도스', 'BRB'],
  ['BY', 'Белару́сь', 'Belarus', 'Republic of Belarus', '벨라루스', 'BLR'],
  ['BE', 'Belgien', 'Belgium', 'Kingdom of Belgium', '벨기에', 'BEL'],
  ['BZ', 'Belize', 'Belize', 'Belize', '벨리즈', 'BLZ'],
  ['BJ', 'Bénin', 'Benin', 'Republic of Benin', '베냉', 'BEN'],
  ['BM', 'Bermuda', 'Bermuda', 'Bermuda', '버뮤다', 'BMU'],
  ['BT', 'འབྲུག་ཡུལ་', 'Bhutan', 'Kingdom of Bhutan', '부탄', 'BTN'],
  ['BO', 'Wuliwya', 'Bolivia', 'Plurinational State of Bolivia', '볼리비아', 'BOL'],
  [
    'BA',
    'Bosna i Hercegovina',
    'Bosnia and Herzegovina',
    'Bosnia and Herzegovina',
    '보스니아 헤르체고비나',
  ],
  ['BW', 'Botswana', 'Botswana', 'Republic of Botswana', '보츠와나', 'BWA'],
  ['BV', 'Bouvetøya', 'Bouvet Island', 'Bouvet Island', '부베 섬', 'BVT'],
  ['BR', 'Brasil', 'Brazil', 'Federative Republic of Brazil', '브라질', 'BRA'],
  [
    'IO',
    'British Indian Ocean Territory',
    'British Indian Ocean Territory',
    'British Indian Ocean Territory',
    '인도',
  ],
  [
    'VG',
    'British Virgin Islands',
    'British Virgin Islands',
    'Virgin Islands',
    '영국령 버진아일랜드',
  ],
  [
    'BN',
    'Negara Brunei Darussalam',
    'Brunei',
    'Nation of Brunei, Abode of Peace',
    '브루나이',
    'BRN',
  ],
  ['BG', 'България', 'Bulgaria', 'Republic of Bulgaria', '불가리아', 'BGR'],
  ['BF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', '부르키나파소', 'BFA'],
  ['BI', 'Burundi', 'Burundi', 'Republic of Burundi', '부룬디', 'BDI'],
  ['KH', 'Kâmpŭchéa', 'Cambodia', 'Kingdom of Cambodia', '캄보디아', 'KHM'],
  ['CM', 'Cameroun', 'Cameroon', 'Republic of Cameroon', '카메룬', 'CMR'],
  ['CA', 'Canada', 'Canada', 'Canada', '캐나다', 'CAN'],
  ['CV', 'Cabo Verde', 'Cape Verde', 'Republic of Cabo Verde', '카보베르데', 'CPV'],
  [
    'BQ',
    'Caribisch Nederland',
    'Caribbean Netherlands',
    'Bonaire, Sint Eustatius and Saba',
    '카리브 네덜란드',
  ],
  ['KY', 'Cayman Islands', 'Cayman Islands', 'Cayman Islands', '케이맨 제도', 'CYM'],
  [
    'CF',
    'République centrafricaine',
    'Central African Republic',
    'Central African Republic',
    '중앙아프리카 공화국',
  ],
  ['TD', 'تشاد', 'Chad', 'Republic of Chad', '차드', 'TCD'],
  ['CL', 'Chile', 'Chile', 'Republic of Chile', '칠레', 'CHL'],
  ['CN', '中国', 'China', "People's Republic of China", '중국', 'CHN'],
  [
    'CX',
    'Christmas Island',
    'Christmas Island',
    'Territory of Christmas Island',
    '크리스마스 섬',
    'CXR',
  ],
  [
    'CC',
    'Cocos (Keeling) Islands',
    'Cocos (Keeling) Islands',
    'Territory of the Cocos (Keeling) Islands',
    '코코스 제도',
  ],
  ['CO', 'Colombia', 'Colombia', 'Republic of Colombia', '콜롬비아', 'COL'],
  ['KM', 'جزر القمر', 'Comoros', 'Union of the Comoros', '코모로', 'COM'],
  ['CK', "Kūki 'Āirani", 'Cook Islands', 'Cook Islands', '쿡 제도', 'COK'],
  ['CR', 'Costa Rica', 'Costa Rica', 'Republic of Costa Rica', '코스타리카', 'CRI'],
  ['HR', 'Hrvatska', 'Croatia', 'Republic of Croatia', '크로아티아', 'HRV'],
  ['CU', 'Cuba', 'Cuba', 'Republic of Cuba', '쿠바', 'CUB'],
  ['CW', 'Curaçao', 'Curaçao', 'Country of Curaçao', '퀴라소', 'CUW'],
  ['CY', 'Κύπρος', 'Cyprus', 'Republic of Cyprus', '키프로스', 'CYP'],
  ['CZ', 'Česko', 'Czechia', 'Czech Republic', '체코', 'CZE'],
  ['DK', 'Danmark', 'Denmark', 'Kingdom of Denmark', '덴마크', 'DNK'],
  ['DJ', 'جيبوتي', 'Djibouti', 'Republic of Djibouti', '지부티', 'DJI'],
  ['DM', 'Dominica', 'Dominica', 'Commonwealth of Dominica', '도미니카 공화국', 'DMA'],
  [
    'DO',
    'República Dominicana',
    'Dominican Republic',
    'Dominican Republic',
    '도미니카 공화국',
    'DOM',
  ],
  ['CD', 'RD Congo', 'DR Congo', 'Democratic Republic of the Congo', '콩고 민주 공화국', 'COD'],
  ['EC', 'Ecuador', 'Ecuador', 'Republic of Ecuador', '에콰도르', 'ECU'],
  ['EG', 'مصر', 'Egypt', 'Arab Republic of Egypt', '이집트', 'EGY'],
  ['SV', 'El Salvador', 'El Salvador', 'Republic of El Salvador', '엘살바도르', 'SLV'],
  [
    'GQ',
    'Guinée équatoriale',
    'Equatorial Guinea',
    'Republic of Equatorial Guinea',
    '적도 기니',
    'GNQ',
  ],
  ['ER', 'إريتريا', 'Eritrea', 'State of Eritrea', '에리트레아', 'ERI'],
  ['EE', 'Eesti', 'Estonia', 'Republic of Estonia', '에스토니아', 'EST'],
  ['SZ', 'eSwatini', 'Eswatini', 'Kingdom of Eswatini', '에스와티니', 'SWZ'],
  ['ET', 'ኢትዮጵያ', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', '에티오피아', 'ETH'],
  ['FK', 'Falkland Islands', 'Falkland Islands', 'Falkland Islands', '포클랜드 제도', 'FLK'],
  ['FO', 'Færøerne', 'Faroe Islands', 'Faroe Islands', '페로 제도', 'FRO'],
  ['FJ', 'Viti', 'Fiji', 'Republic of Fiji', '피지', 'FJI'],
  ['FI', 'Suomi', 'Finland', 'Republic of Finland', '핀란드', 'FIN'],
  ['FR', 'France', 'France', 'French Republic', '프랑스', 'FRA'],
  ['GF', 'Guyane française', 'French Guiana', 'Guiana', '프랑스령 기아나', 'GUF'],
  [
    'PF',
    'Polynésie française',
    'French Polynesia',
    'French Polynesia',
    '프랑스령 폴리네시아',
    'PYF',
  ],
  [
    'TF',
    'Terres australes et antarctiques françaises',
    'French Southern and Antarctic Lands',
    'Territory of the French Southern and Antarctic Lands',
    '프랑스령 남부와 남극 지역',
  ],
  ['GA', 'Gabon', 'Gabon', 'Gabonese Republic', '가봉', 'GAB'],
  ['GM', 'Gambia', 'Gambia', 'Republic of the Gambia', '감비아', 'GMB'],
  ['GE', 'საქართველო', 'Georgia', 'Georgia', '조지아', 'GEO'],
  ['DE', 'Deutschland', 'Germany', 'Federal Republic of Germany', '독일', 'DEU'],
  ['GH', 'Ghana', 'Ghana', 'Republic of Ghana', '가나', 'GHA'],
  ['GI', 'Gibraltar', 'Gibraltar', 'Gibraltar', '지브롤터', 'GIB'],
  ['GR', 'Ελλάδα', 'Greece', 'Hellenic Republic', '그리스', 'GRC'],
  ['GL', 'Kalaallit Nunaat', 'Greenland', 'Greenland', '그린란드', 'GRL'],
  ['GD', 'Grenada', 'Grenada', 'Grenada', '그레나다', 'GRD'],
  ['GP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', '과들루프', 'GLP'],
  ['GU', 'Guåhån', 'Guam', 'Guam', '괌', 'GUM'],
  ['GT', 'Guatemala', 'Guatemala', 'Republic of Guatemala', '과테말라', 'GTM'],
  ['GG', 'Guernesey', 'Guernsey', 'Bailiwick of Guernsey', '건지 섬', 'GGY'],
  ['GN', 'Guinée', 'Guinea', 'Republic of Guinea', '기니', 'GIN'],
  ['GW', 'Guiné-Bissau', 'Guinea-Bissau', 'Republic of Guinea-Bissau', '기니비사우', 'GNB'],
  ['GY', 'Guyana', 'Guyana', 'Co-operative Republic of Guyana', '가이아나', 'GUY'],
  ['HT', 'Haïti', 'Haiti', 'Republic of Haiti', '아이티', 'HTI'],
  [
    'HM',
    'Heard Island and McDonald Islands',
    'Heard Island and McDonald Islands',
    'Heard Island and McDonald Islands',
    '허드 맥도널드 제도',
  ],
  ['HN', 'Honduras', 'Honduras', 'Republic of Honduras', '온두라스', 'HND'],
  [
    'HK',
    '香港',
    'Hong Kong',
    "Hong Kong Special Administrative Region of the People's Republic of China",
    '홍콩',
  ],
  ['HU', 'Magyarország', 'Hungary', 'Hungary', '헝가리', 'HUN'],
  ['IS', 'Ísland', 'Iceland', 'Iceland', '아이슬란드', 'ISL'],
  ['IN', 'भारत', 'India', 'Republic of India', '인도', 'IND'],
  ['ID', 'Indonesia', 'Indonesia', 'Republic of Indonesia', '인도네시아', 'IDN'],
  ['IR', 'ایران', 'Iran', 'Islamic Republic of Iran', '이란', 'IRN'],
  ['IQ', 'العراق', 'Iraq', 'Republic of Iraq', '이라크', 'IRQ'],
  ['IE', 'Éire', 'Ireland', 'Republic of Ireland', '아일랜드', 'IRL'],
  ['IM', 'Mannin', 'Isle of Man', 'Isle of Man', '맨섬', 'IMN'],
  ['IL', 'إسرائيل', 'Israel', 'State of Israel', '이스라엘', 'ISR'],
  ['IT', 'Italia', 'Italy', 'Italian Republic', '이탈리아', 'ITA'],
  ['CI', "Côte d'Ivoire", 'Ivory Coast', "Republic of Côte d'Ivoire", '코트디부아르', 'CIV'],
  ['JM', 'Jamaica', 'Jamaica', 'Jamaica', '자메이카', 'JAM'],
  ['JP', '日本', 'Japan', 'Japan', '일본', 'JPN'],
  ['JE', 'Jersey', 'Jersey', 'Bailiwick of Jersey', '저지 섬', 'JEY'],
  ['JO', 'الأردن', 'Jordan', 'Hashemite Kingdom of Jordan', '요르단', 'JOR'],
  ['KZ', 'Қазақстан', 'Kazakhstan', 'Republic of Kazakhstan', '카자흐스탄', 'KAZ'],
  ['KE', 'Kenya', 'Kenya', 'Republic of Kenya', '케냐', 'KEN'],
  [
    'KI',
    'Kiribati',
    'Kiribati',
    'Independent and Sovereign Republic of Kiribati',
    '키리바시',
    'KIR',
  ],
  ['KW', 'الكويت', 'Kuwait', 'State of Kuwait', '쿠웨이트', 'KWT'],
  ['KG', 'Кыргызстан', 'Kyrgyzstan', 'Kyrgyz Republic', '키르기스스탄', 'KGZ'],
  ['LA', 'ສປປລາວ', 'Laos', "Lao People's Democratic Republic", '라오스', 'LAO'],
  ['LV', 'Latvija', 'Latvia', 'Republic of Latvia', '라트비아', 'LVA'],
  ['LB', 'لبنان', 'Lebanon', 'Lebanese Republic', '레바논', 'LBN'],
  ['LS', 'Lesotho', 'Lesotho', 'Kingdom of Lesotho', '레소토', 'LSO'],
  ['LR', 'Liberia', 'Liberia', 'Republic of Liberia', '라이베리아', 'LBR'],
  ['LY', 'ليبيا', 'Libya', 'State of Libya', '리비아', 'LBY'],
  ['LI', 'Liechtenstein', 'Liechtenstein', 'Principality of Liechtenstein', '리히텐슈타인', 'LIE'],
  ['LT', 'Lietuva', 'Lithuania', 'Republic of Lithuania', '리투아니아', 'LTU'],
  ['LU', 'Luxemburg', 'Luxembourg', 'Grand Duchy of Luxembourg', '룩셈부르크', 'LUX'],
  [
    'MO',
    'Macau',
    'Macau',
    "Macao Special Administrative Region of the People's Republic of China",
    '마카오',
  ],
  ['MG', 'Madagascar', 'Madagascar', 'Republic of Madagascar', '마다가스카르', 'MDG'],
  ['MW', 'Malaŵi', 'Malawi', 'Republic of Malawi', '말라위', 'MWI'],
  ['MY', 'مليسيا', 'Malaysia', 'Malaysia', '말레이시아', 'MYS'],
  ['MV', 'ދިވެހިރާއްޖޭގެ', 'Maldives', 'Republic of the Maldives', '몰디브', 'MDV'],
  ['ML', 'Mali', 'Mali', 'Republic of Mali', '말리', 'MLI'],
  ['MT', 'Malta', 'Malta', 'Republic of Malta', '몰타', 'MLT'],
  ['MH', 'M̧ajeļ', 'Marshall Islands', 'Republic of the Marshall Islands', '마셜 제도', 'MHL'],
  ['MQ', 'Martinique', 'Martinique', 'Martinique', '마르티니크', 'MTQ'],
  ['MR', 'موريتانيا', 'Mauritania', 'Islamic Republic of Mauritania', '모리타니', 'MRT'],
  ['MU', 'Maurice', 'Mauritius', 'Republic of Mauritius', '모리셔스', 'MUS'],
  ['YT', 'Mayotte', 'Mayotte', 'Department of Mayotte', '마요트', 'MYT'],
  ['MX', 'México', 'Mexico', 'United Mexican States', '멕시코', 'MEX'],
  ['FM', 'Micronesia', 'Micronesia', 'Federated States of Micronesia', '미크로네시아', 'FSM'],
  ['MD', 'Moldova', 'Moldova', 'Republic of Moldova', '몰도바', 'MDA'],
  ['MC', 'Monaco', 'Monaco', 'Principality of Monaco', '모나코', 'MCO'],
  ['MN', 'Монгол улс', 'Mongolia', 'Mongolia', '몽골국', 'MNG'],
  ['ME', 'Црна Гора', 'Montenegro', 'Montenegro', '몬테네그로', 'MNE'],
  ['MS', 'Montserrat', 'Montserrat', 'Montserrat', '몬트세랫', 'MSR'],
  ['MA', 'المغرب', 'Morocco', 'Kingdom of Morocco', '모로코', 'MAR'],
  ['MZ', 'Moçambique', 'Mozambique', 'Republic of Mozambique', '모잠비크', 'MOZ'],
  ['MM', 'မြန်မာ', 'Myanmar', 'Republic of the Union of Myanmar', '미얀마', 'MMR'],
  ['NA', 'Namibië', 'Namibia', 'Republic of Namibia', '나미비아', 'NAM'],
  ['NR', 'Nauru', 'Nauru', 'Republic of Nauru', '나우루', 'NRU'],
  ['NP', 'नेपाल', 'Nepal', 'Federal Democratic Republic of Nepal', '네팔', 'NPL'],
  ['NL', 'Nederland', 'Netherlands', 'Kingdom of the Netherlands', '네덜란드', 'NLD'],
  ['NC', 'Nouvelle-Calédonie', 'New Caledonia', 'New Caledonia', '누벨칼레도니', 'NCL'],
  ['NZ', 'Aotearoa', 'New Zealand', 'New Zealand', '뉴질랜드', 'NZL'],
  ['NI', 'Nicaragua', 'Nicaragua', 'Republic of Nicaragua', '니카라과', 'NIC'],
  ['NE', 'Niger', 'Niger', 'Republic of Niger', '니제르', 'NER'],
  ['NG', 'Nigeria', 'Nigeria', 'Federal Republic of Nigeria', '나이지리아', 'NGA'],
  ['NU', 'Niuē', 'Niue', 'Niue', '니우에', 'NIU'],
  ['NF', "Norf'k Ailen", 'Norfolk Island', 'Territory of Norfolk Island', '노퍽 섬', 'NFK'],
  ['KP', '조선', 'North Korea', "Democratic People's Republic of Korea", '조선', 'PRK'],
  ['MK', 'Македонија', 'North Macedonia', 'Republic of North Macedonia', '북마케도니아', 'MKD'],
  [
    'MP',
    'Northern Mariana Islands',
    'Northern Mariana Islands',
    'Commonwealth of the Northern Mariana Islands',
    '북마리아나 제도',
  ],
  ['NO', 'Noreg', 'Norway', 'Kingdom of Norway', '노르웨이', 'NOR'],
  ['OM', 'عمان', 'Oman', 'Sultanate of Oman', '오만', 'OMN'],
  ['PK', 'پاكستان', 'Pakistan', 'Islamic Republic of Pakistan', '파키스탄', 'PAK'],
  ['PW', 'Belau', 'Palau', 'Republic of Palau', '팔라우', 'PLW'],
  ['PS', 'فلسطين', 'Palestine', 'State of Palestine', '팔레스타인', 'PSE'],
  ['PA', 'Panamá', 'Panama', 'Republic of Panama', '파나마', 'PAN'],
  [
    'PG',
    'Papua Niu Gini',
    'Papua New Guinea',
    'Independent State of Papua New Guinea',
    '파푸아뉴기니',
  ],
  ['PY', 'Paraguái', 'Paraguay', 'Republic of Paraguay', '파라과이', 'PRY'],
  ['PE', 'Piruw', 'Peru', 'Republic of Peru', '페루', 'PER'],
  ['PH', 'Pilipinas', 'Philippines', 'Republic of the Philippines', '필리핀', 'PHL'],
  ['PN', 'Pitcairn Islands', 'Pitcairn Islands', 'Pitcairn Group of Islands', '핏케언 제도', 'PCN'],
  ['PL', 'Polska', 'Poland', 'Republic of Poland', '폴란드', 'POL'],
  ['PT', 'Portugal', 'Portugal', 'Portuguese Republic', '포르투갈', 'PRT'],
  ['PR', 'Puerto Rico', 'Puerto Rico', 'Commonwealth of Puerto Rico', '푸에르토리코', 'PRI'],
  ['QA', 'قطر', 'Qatar', 'State of Qatar', '카타르', 'QAT'],
  ['CG', 'République du Congo', 'Republic of the Congo', 'Republic of the Congo', '콩고', 'COG'],
  ['RE', 'La Réunion', 'Réunion', 'Réunion Island', '레위니옹', 'REU'],
  ['RO', 'România', 'Romania', 'Romania', '루마니아', 'ROU'],
  ['RU', 'Россия', 'Russia', 'Russian Federation', '러시아', 'RUS'],
  ['RW', 'Rwanda', 'Rwanda', 'Republic of Rwanda', '르완다', 'RWA'],
  [
    'BL',
    'Saint-Barthélemy',
    'Saint Barthélemy',
    'Collectivity of Saint Barthélemy',
    '생바르텔레미',
  ],
  [
    'SH',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Helena, Ascension and Tristan da Cunha',
    '세인트헬레나',
  ],
  [
    'KN',
    'Saint Kitts and Nevis',
    'Saint Kitts and Nevis',
    'Federation of Saint Christopher and Nevis',
    '세인트키츠 네비스',
  ],
  ['LC', 'Saint Lucia', 'Saint Lucia', 'Saint Lucia', '세인트루시아', 'LCA'],
  ['MF', 'Saint-Martin', 'Saint Martin', 'Saint Martin', '생마르탱', 'MAF'],
  [
    'PM',
    'Saint-Pierre-et-Miquelon',
    'Saint Pierre and Miquelon',
    'Saint Pierre and Miquelon',
    '생피에르 미클롱',
  ],
  [
    'VC',
    'Saint Vincent and the Grenadines',
    'Saint Vincent and the Grenadines',
    'Saint Vincent and the Grenadines',
    '세인트빈센트 그레나딘',
  ],
  ['WS', 'Sāmoa', 'Samoa', 'Independent State of Samoa', '사모아', 'WSM'],
  ['SM', 'San Marino', 'San Marino', 'Most Serene Republic of San Marino', '산마리노', 'SMR'],
  [
    'ST',
    'São Tomé e Príncipe',
    'São Tomé and Príncipe',
    'Democratic Republic of São Tomé and Príncipe',
    '상투메 프린시페',
  ],
  ['SA', 'السعودية', 'Saudi Arabia', 'Kingdom of Saudi Arabia', '사우디아라비아', 'SAU'],
  ['SN', 'Sénégal', 'Senegal', 'Republic of Senegal', '세네갈', 'SEN'],
  ['RS', 'Србија', 'Serbia', 'Republic of Serbia', '세르비아', 'SRB'],
  ['SC', 'Sesel', 'Seychelles', 'Republic of Seychelles', '세이셸', 'SYC'],
  ['SL', 'Sierra Leone', 'Sierra Leone', 'Republic of Sierra Leone', '시에라리온', 'SLE'],
  ['SG', 'Singapura', 'Singapore', 'Republic of Singapore', '싱가포르', 'SGP'],
  ['SX', 'Saint-Martin', 'Sint Maarten', 'Sint Maarten', '신트마르턴', 'SXM'],
  ['SK', 'Slovensko', 'Slovakia', 'Slovak Republic', '슬로바키아', 'SVK'],
  ['SI', 'Slovenija', 'Slovenia', 'Republic of Slovenia', '슬로베니아', 'SVN'],
  ['SB', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands', '솔로몬 제도', 'SLB'],
  ['SO', 'الصومال', 'Somalia', 'Federal Republic of Somalia', '소말리아', 'SOM'],
  ['ZA', 'South Africa', 'South Africa', 'Republic of South Africa', '남아프리카', 'ZAF'],
  [
    'GS',
    'South Georgia',
    'South Georgia',
    'South Georgia and the South Sandwich Islands',
    '조지아',
  ],
  ['SS', 'South Sudan', 'South Sudan', 'Republic of South Sudan', '남수단', 'SSD'],
  ['ES', 'España', 'Spain', 'Kingdom of Spain', '스페인', 'ESP'],
  [
    'LK',
    'ශ්‍රී ලංකාව',
    'Sri Lanka',
    'Democratic Socialist Republic of Sri Lanka',
    '스리랑카',
    'LKA',
  ],
  ['SD', 'السودان', 'Sudan', 'Republic of the Sudan', '수단', 'SDN'],
  ['SR', 'Suriname', 'Suriname', 'Republic of Suriname', '수리남', 'SUR'],
  [
    'SJ',
    'Svalbard og Jan Mayen',
    'Svalbard and Jan Mayen',
    'Svalbard og Jan Mayen',
    '스발바르 얀마옌 제도',
  ],
  ['SE', 'Sverige', 'Sweden', 'Kingdom of Sweden', '스웨덴', 'SWE'],
  ['CH', 'Suisse', 'Switzerland', 'Swiss Confederation', '스위스', 'CHE'],
  ['SY', 'سوريا', 'Syria', 'Syrian Arab Republic', '시리아', 'SYR'],
  ['TW', '台灣', 'Taiwan', 'Republic of China (Taiwan)', '대만', 'TWN'],
  ['TJ', 'Таджикистан', 'Tajikistan', 'Republic of Tajikistan', '타지키스탄', 'TJK'],
  ['TZ', 'Tanzania', 'Tanzania', 'United Republic of Tanzania', '탄자니아', 'TZA'],
  ['TH', 'ประเทศไทย', 'Thailand', 'Kingdom of Thailand', '태국', 'THA'],
  ['TL', 'Timor-Leste', 'Timor-Leste', 'Democratic Republic of Timor-Leste', '동티모르', 'TLS'],
  ['TG', 'Togo', 'Togo', 'Togolese Republic', '토고', 'TGO'],
  ['TK', 'Tokelau', 'Tokelau', 'Tokelau', '토켈라우', 'TKL'],
  ['TO', 'Tonga', 'Tonga', 'Kingdom of Tonga', '통가', 'TON'],
  [
    'TT',
    'Trinidad and Tobago',
    'Trinidad and Tobago',
    'Republic of Trinidad and Tobago',
    '트리니다드 토바고',
  ],
  ['TN', 'تونس', 'Tunisia', 'Tunisian Republic', '튀니지', 'TUN'],
  ['TR', 'Türkiye', 'Türkiye', 'Republic of Türkiye', '터키', 'TUR'],
  ['TM', 'Туркмения', 'Turkmenistan', 'Turkmenistan', '투르크메니스탄', 'TKM'],
  [
    'TC',
    'Turks and Caicos Islands',
    'Turks and Caicos Islands',
    'Turks and Caicos Islands',
    '터크스 케이커스 제도',
  ],
  ['TV', 'Tuvalu', 'Tuvalu', 'Tuvalu', '투발루', 'TUV'],
  ['UG', 'Uganda', 'Uganda', 'Republic of Uganda', '우간다', 'UGA'],
  ['UA', 'Україна', 'Ukraine', 'Ukraine', '우크라이나', 'UKR'],
  ['AE', 'الإمارات', 'United Arab Emirates', 'United Arab Emirates', '아랍에미리트', 'ARE'],
  [
    'GB',
    'United Kingdom',
    'United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland',
    '영국',
  ],
  ['US', 'United States', 'United States', 'United States of America', '미국', 'USA'],
  [
    'UM',
    'United States Minor Outlying Islands',
    'United States Minor Outlying Islands',
    'United States Minor Outlying Islands',
    '미국령 군소 제도',
  ],
  [
    'VI',
    'United States Virgin Islands',
    'United States Virgin Islands',
    'Virgin Islands of the United States',
    '미국령 버진아일랜드',
  ],
  ['UY', 'Uruguay', 'Uruguay', 'Oriental Republic of Uruguay', '우루과이', 'URY'],
  ['UZ', 'Узбекистан', 'Uzbekistan', 'Republic of Uzbekistan', '우즈베키스탄', 'UZB'],
  ['VU', 'Vanuatu', 'Vanuatu', 'Republic of Vanuatu', '바누아투', 'VUT'],
  ['VA', 'Vaticano', 'Vatican City', 'Vatican City State', '바티칸', 'VAT'],
  ['VE', 'Venezuela', 'Venezuela', 'Bolivarian Republic of Venezuela', '베네수엘라', 'VEN'],
  ['VN', 'Việt Nam', 'Vietnam', 'Socialist Republic of Vietnam', '베트남', 'VNM'],
  [
    'WF',
    'Wallis et Futuna',
    'Wallis and Futuna',
    'Territory of the Wallis and Futuna Islands',
    '왈리스 퓌튀나',
  ],
  ['EH', 'Western Sahara', 'Western Sahara', 'Sahrawi Arab Democratic Republic', '서사하라', 'ESH'],
  ['YE', 'اليمن', 'Yemen', 'Republic of Yemen', '예멘', 'YEM'],
  ['ZM', 'Zambia', 'Zambia', 'Republic of Zambia', '잠비아', 'ZMB'],
  ['ZW', 'Zimbabwe', 'Zimbabwe', 'Republic of Zimbabwe', '짐바브웨', 'ZWE'],
]

export const countryOptions = Object.freeze(
  countryRecords.map(([code, nativeName, englishName, apiValue, koreanName, alpha3]) =>
    Object.freeze({ code, nativeName, englishName, apiValue, koreanName, alpha3 }),
  ),
)

const countryOptionByCode = new Map(countryOptions.map((country) => [country.code, country]))

export function getCountryOption(code) {
  return countryOptionByCode.get(code?.toUpperCase()) ?? null
}

/**
 * 저장된 값으로 선택지를 되찾는 표.
 *
 * 백엔드와 여권 지면은 ISO 3166-1 alpha-3(`KOR`)를 주고받는다. 다만 예전에
 * `Republic of Korea` 같은 공식 국명으로 저장된 값이 남아 있을 수 있어 그쪽도
 * 함께 받는다. 셋 다 대문자로 눕혀 두므로 대소문자는 신경 쓰지 않아도 된다.
 */
const countryOptionByStored = new Map(
  countryOptions.flatMap((country) => [
    [country.alpha3, country],
    [country.apiValue.toUpperCase(), country],
  ]),
)

export function findCountryByStoredValue(value) {
  if (!value) return null
  return countryOptionByStored.get(String(value).toUpperCase()) ?? null
}
