// Derived from world-countries 5.1.0 (ODbL-1.0).
// Source: https://github.com/mledoze/countries
// XK (Kosovo) is omitted because it is not an officially assigned ISO 3166-1 code.
const countryRecords = [
  ['KR', '대한민국', 'Republic of Korea', 'Republic of Korea', '한국'],
  ['AF', 'افغانستان', 'Afghanistan', 'Islamic Republic of Afghanistan', '아프가니스탄'],
  ['AX', 'Åland', 'Åland Islands', 'Åland Islands', '올란드 제도'],
  ['AL', 'Shqipëria', 'Albania', 'Republic of Albania', '알바니아'],
  ['DZ', 'الجزائر', 'Algeria', "People's Democratic Republic of Algeria", '알제리'],
  ['AS', 'Sāmoa Amelika', 'American Samoa', 'American Samoa', '아메리칸사모아'],
  ['AD', 'Andorra', 'Andorra', 'Principality of Andorra', '안도라'],
  ['AO', 'Angola', 'Angola', 'Republic of Angola', '앙골라'],
  ['AI', 'Anguilla', 'Anguilla', 'Anguilla', '앵귈라'],
  ['AQ', 'Antarctica', 'Antarctica', 'Antarctica', '남극'],
  ['AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Antigua and Barbuda', '앤티가 바부다'],
  ['AR', 'Argentina', 'Argentina', 'Argentine Republic', '아르헨티나'],
  ['AM', 'Հայաստան', 'Armenia', 'Republic of Armenia', '아르메니아'],
  ['AW', 'Aruba', 'Aruba', 'Aruba', '아루바'],
  ['AU', 'Australia', 'Australia', 'Commonwealth of Australia', '호주'],
  ['AT', 'Österreich', 'Austria', 'Republic of Austria', '오스트리아'],
  ['AZ', 'Azərbaycan', 'Azerbaijan', 'Republic of Azerbaijan', '아제르바이잔'],
  ['BS', 'Bahamas', 'Bahamas', 'Commonwealth of the Bahamas', '바하마'],
  ['BH', 'البحرين', 'Bahrain', 'Kingdom of Bahrain', '바레인'],
  ['BD', 'বাংলাদেশ', 'Bangladesh', "People's Republic of Bangladesh", '방글라데시'],
  ['BB', 'Barbados', 'Barbados', 'Barbados', '바베이도스'],
  ['BY', 'Белару́сь', 'Belarus', 'Republic of Belarus', '벨라루스'],
  ['BE', 'Belgien', 'Belgium', 'Kingdom of Belgium', '벨기에'],
  ['BZ', 'Belize', 'Belize', 'Belize', '벨리즈'],
  ['BJ', 'Bénin', 'Benin', 'Republic of Benin', '베냉'],
  ['BM', 'Bermuda', 'Bermuda', 'Bermuda', '버뮤다'],
  ['BT', 'འབྲུག་ཡུལ་', 'Bhutan', 'Kingdom of Bhutan', '부탄'],
  ['BO', 'Wuliwya', 'Bolivia', 'Plurinational State of Bolivia', '볼리비아'],
  [
    'BA',
    'Bosna i Hercegovina',
    'Bosnia and Herzegovina',
    'Bosnia and Herzegovina',
    '보스니아 헤르체고비나',
  ],
  ['BW', 'Botswana', 'Botswana', 'Republic of Botswana', '보츠와나'],
  ['BV', 'Bouvetøya', 'Bouvet Island', 'Bouvet Island', '부베 섬'],
  ['BR', 'Brasil', 'Brazil', 'Federative Republic of Brazil', '브라질'],
  [
    'IO',
    'British Indian Ocean Territory',
    'British Indian Ocean Territory',
    'British Indian Ocean Territory',
    '인도',
  ],
  [
    'VG',
    'British Virgin Islands',
    'British Virgin Islands',
    'Virgin Islands',
    '영국령 버진아일랜드',
  ],
  ['BN', 'Negara Brunei Darussalam', 'Brunei', 'Nation of Brunei, Abode of Peace', '브루나이'],
  ['BG', 'България', 'Bulgaria', 'Republic of Bulgaria', '불가리아'],
  ['BF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', '부르키나파소'],
  ['BI', 'Burundi', 'Burundi', 'Republic of Burundi', '부룬디'],
  ['KH', 'Kâmpŭchéa', 'Cambodia', 'Kingdom of Cambodia', '캄보디아'],
  ['CM', 'Cameroun', 'Cameroon', 'Republic of Cameroon', '카메룬'],
  ['CA', 'Canada', 'Canada', 'Canada', '캐나다'],
  ['CV', 'Cabo Verde', 'Cape Verde', 'Republic of Cabo Verde', '카보베르데'],
  [
    'BQ',
    'Caribisch Nederland',
    'Caribbean Netherlands',
    'Bonaire, Sint Eustatius and Saba',
    '카리브 네덜란드',
  ],
  ['KY', 'Cayman Islands', 'Cayman Islands', 'Cayman Islands', '케이맨 제도'],
  [
    'CF',
    'République centrafricaine',
    'Central African Republic',
    'Central African Republic',
    '중앙아프리카 공화국',
  ],
  ['TD', 'تشاد', 'Chad', 'Republic of Chad', '차드'],
  ['CL', 'Chile', 'Chile', 'Republic of Chile', '칠레'],
  ['CN', '中国', 'China', "People's Republic of China", '중국'],
  ['CX', 'Christmas Island', 'Christmas Island', 'Territory of Christmas Island', '크리스마스 섬'],
  [
    'CC',
    'Cocos (Keeling) Islands',
    'Cocos (Keeling) Islands',
    'Territory of the Cocos (Keeling) Islands',
    '코코스 제도',
  ],
  ['CO', 'Colombia', 'Colombia', 'Republic of Colombia', '콜롬비아'],
  ['KM', 'جزر القمر', 'Comoros', 'Union of the Comoros', '코모로'],
  ['CK', "Kūki 'Āirani", 'Cook Islands', 'Cook Islands', '쿡 제도'],
  ['CR', 'Costa Rica', 'Costa Rica', 'Republic of Costa Rica', '코스타리카'],
  ['HR', 'Hrvatska', 'Croatia', 'Republic of Croatia', '크로아티아'],
  ['CU', 'Cuba', 'Cuba', 'Republic of Cuba', '쿠바'],
  ['CW', 'Curaçao', 'Curaçao', 'Country of Curaçao', '퀴라소'],
  ['CY', 'Κύπρος', 'Cyprus', 'Republic of Cyprus', '키프로스'],
  ['CZ', 'Česko', 'Czechia', 'Czech Republic', '체코'],
  ['DK', 'Danmark', 'Denmark', 'Kingdom of Denmark', '덴마크'],
  ['DJ', 'جيبوتي', 'Djibouti', 'Republic of Djibouti', '지부티'],
  ['DM', 'Dominica', 'Dominica', 'Commonwealth of Dominica', '도미니카 공화국'],
  ['DO', 'República Dominicana', 'Dominican Republic', 'Dominican Republic', '도미니카 공화국'],
  ['CD', 'RD Congo', 'DR Congo', 'Democratic Republic of the Congo', '콩고 민주 공화국'],
  ['EC', 'Ecuador', 'Ecuador', 'Republic of Ecuador', '에콰도르'],
  ['EG', 'مصر', 'Egypt', 'Arab Republic of Egypt', '이집트'],
  ['SV', 'El Salvador', 'El Salvador', 'Republic of El Salvador', '엘살바도르'],
  ['GQ', 'Guinée équatoriale', 'Equatorial Guinea', 'Republic of Equatorial Guinea', '적도 기니'],
  ['ER', 'إريتريا', 'Eritrea', 'State of Eritrea', '에리트레아'],
  ['EE', 'Eesti', 'Estonia', 'Republic of Estonia', '에스토니아'],
  ['SZ', 'eSwatini', 'Eswatini', 'Kingdom of Eswatini', '에스와티니'],
  ['ET', 'ኢትዮጵያ', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', '에티오피아'],
  ['FK', 'Falkland Islands', 'Falkland Islands', 'Falkland Islands', '포클랜드 제도'],
  ['FO', 'Færøerne', 'Faroe Islands', 'Faroe Islands', '페로 제도'],
  ['FJ', 'Viti', 'Fiji', 'Republic of Fiji', '피지'],
  ['FI', 'Suomi', 'Finland', 'Republic of Finland', '핀란드'],
  ['FR', 'France', 'France', 'French Republic', '프랑스'],
  ['GF', 'Guyane française', 'French Guiana', 'Guiana', '프랑스령 기아나'],
  ['PF', 'Polynésie française', 'French Polynesia', 'French Polynesia', '프랑스령 폴리네시아'],
  [
    'TF',
    'Terres australes et antarctiques françaises',
    'French Southern and Antarctic Lands',
    'Territory of the French Southern and Antarctic Lands',
    '프랑스령 남부와 남극 지역',
  ],
  ['GA', 'Gabon', 'Gabon', 'Gabonese Republic', '가봉'],
  ['GM', 'Gambia', 'Gambia', 'Republic of the Gambia', '감비아'],
  ['GE', 'საქართველო', 'Georgia', 'Georgia', '조지아'],
  ['DE', 'Deutschland', 'Germany', 'Federal Republic of Germany', '독일'],
  ['GH', 'Ghana', 'Ghana', 'Republic of Ghana', '가나'],
  ['GI', 'Gibraltar', 'Gibraltar', 'Gibraltar', '지브롤터'],
  ['GR', 'Ελλάδα', 'Greece', 'Hellenic Republic', '그리스'],
  ['GL', 'Kalaallit Nunaat', 'Greenland', 'Greenland', '그린란드'],
  ['GD', 'Grenada', 'Grenada', 'Grenada', '그레나다'],
  ['GP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', '과들루프'],
  ['GU', 'Guåhån', 'Guam', 'Guam', '괌'],
  ['GT', 'Guatemala', 'Guatemala', 'Republic of Guatemala', '과테말라'],
  ['GG', 'Guernesey', 'Guernsey', 'Bailiwick of Guernsey', '건지 섬'],
  ['GN', 'Guinée', 'Guinea', 'Republic of Guinea', '기니'],
  ['GW', 'Guiné-Bissau', 'Guinea-Bissau', 'Republic of Guinea-Bissau', '기니비사우'],
  ['GY', 'Guyana', 'Guyana', 'Co-operative Republic of Guyana', '가이아나'],
  ['HT', 'Haïti', 'Haiti', 'Republic of Haiti', '아이티'],
  [
    'HM',
    'Heard Island and McDonald Islands',
    'Heard Island and McDonald Islands',
    'Heard Island and McDonald Islands',
    '허드 맥도널드 제도',
  ],
  ['HN', 'Honduras', 'Honduras', 'Republic of Honduras', '온두라스'],
  [
    'HK',
    '香港',
    'Hong Kong',
    "Hong Kong Special Administrative Region of the People's Republic of China",
    '홍콩',
  ],
  ['HU', 'Magyarország', 'Hungary', 'Hungary', '헝가리'],
  ['IS', 'Ísland', 'Iceland', 'Iceland', '아이슬란드'],
  ['IN', 'भारत', 'India', 'Republic of India', '인도'],
  ['ID', 'Indonesia', 'Indonesia', 'Republic of Indonesia', '인도네시아'],
  ['IR', 'ایران', 'Iran', 'Islamic Republic of Iran', '이란'],
  ['IQ', 'العراق', 'Iraq', 'Republic of Iraq', '이라크'],
  ['IE', 'Éire', 'Ireland', 'Republic of Ireland', '아일랜드'],
  ['IM', 'Mannin', 'Isle of Man', 'Isle of Man', '맨섬'],
  ['IL', 'إسرائيل', 'Israel', 'State of Israel', '이스라엘'],
  ['IT', 'Italia', 'Italy', 'Italian Republic', '이탈리아'],
  ['CI', "Côte d'Ivoire", 'Ivory Coast', "Republic of Côte d'Ivoire", '코트디부아르'],
  ['JM', 'Jamaica', 'Jamaica', 'Jamaica', '자메이카'],
  ['JP', '日本', 'Japan', 'Japan', '일본'],
  ['JE', 'Jersey', 'Jersey', 'Bailiwick of Jersey', '저지 섬'],
  ['JO', 'الأردن', 'Jordan', 'Hashemite Kingdom of Jordan', '요르단'],
  ['KZ', 'Қазақстан', 'Kazakhstan', 'Republic of Kazakhstan', '카자흐스탄'],
  ['KE', 'Kenya', 'Kenya', 'Republic of Kenya', '케냐'],
  ['KI', 'Kiribati', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', '키리바시'],
  ['KW', 'الكويت', 'Kuwait', 'State of Kuwait', '쿠웨이트'],
  ['KG', 'Кыргызстан', 'Kyrgyzstan', 'Kyrgyz Republic', '키르기스스탄'],
  ['LA', 'ສປປລາວ', 'Laos', "Lao People's Democratic Republic", '라오스'],
  ['LV', 'Latvija', 'Latvia', 'Republic of Latvia', '라트비아'],
  ['LB', 'لبنان', 'Lebanon', 'Lebanese Republic', '레바논'],
  ['LS', 'Lesotho', 'Lesotho', 'Kingdom of Lesotho', '레소토'],
  ['LR', 'Liberia', 'Liberia', 'Republic of Liberia', '라이베리아'],
  ['LY', 'ليبيا', 'Libya', 'State of Libya', '리비아'],
  ['LI', 'Liechtenstein', 'Liechtenstein', 'Principality of Liechtenstein', '리히텐슈타인'],
  ['LT', 'Lietuva', 'Lithuania', 'Republic of Lithuania', '리투아니아'],
  ['LU', 'Luxemburg', 'Luxembourg', 'Grand Duchy of Luxembourg', '룩셈부르크'],
  [
    'MO',
    'Macau',
    'Macau',
    "Macao Special Administrative Region of the People's Republic of China",
    '마카오',
  ],
  ['MG', 'Madagascar', 'Madagascar', 'Republic of Madagascar', '마다가스카르'],
  ['MW', 'Malaŵi', 'Malawi', 'Republic of Malawi', '말라위'],
  ['MY', 'مليسيا', 'Malaysia', 'Malaysia', '말레이시아'],
  ['MV', 'ދިވެހިރާއްޖޭގެ', 'Maldives', 'Republic of the Maldives', '몰디브'],
  ['ML', 'Mali', 'Mali', 'Republic of Mali', '말리'],
  ['MT', 'Malta', 'Malta', 'Republic of Malta', '몰타'],
  ['MH', 'M̧ajeļ', 'Marshall Islands', 'Republic of the Marshall Islands', '마셜 제도'],
  ['MQ', 'Martinique', 'Martinique', 'Martinique', '마르티니크'],
  ['MR', 'موريتانيا', 'Mauritania', 'Islamic Republic of Mauritania', '모리타니'],
  ['MU', 'Maurice', 'Mauritius', 'Republic of Mauritius', '모리셔스'],
  ['YT', 'Mayotte', 'Mayotte', 'Department of Mayotte', '마요트'],
  ['MX', 'México', 'Mexico', 'United Mexican States', '멕시코'],
  ['FM', 'Micronesia', 'Micronesia', 'Federated States of Micronesia', '미크로네시아'],
  ['MD', 'Moldova', 'Moldova', 'Republic of Moldova', '몰도바'],
  ['MC', 'Monaco', 'Monaco', 'Principality of Monaco', '모나코'],
  ['MN', 'Монгол улс', 'Mongolia', 'Mongolia', '몽골국'],
  ['ME', 'Црна Гора', 'Montenegro', 'Montenegro', '몬테네그로'],
  ['MS', 'Montserrat', 'Montserrat', 'Montserrat', '몬트세랫'],
  ['MA', 'المغرب', 'Morocco', 'Kingdom of Morocco', '모로코'],
  ['MZ', 'Moçambique', 'Mozambique', 'Republic of Mozambique', '모잠비크'],
  ['MM', 'မြန်မာ', 'Myanmar', 'Republic of the Union of Myanmar', '미얀마'],
  ['NA', 'Namibië', 'Namibia', 'Republic of Namibia', '나미비아'],
  ['NR', 'Nauru', 'Nauru', 'Republic of Nauru', '나우루'],
  ['NP', 'नेपाल', 'Nepal', 'Federal Democratic Republic of Nepal', '네팔'],
  ['NL', 'Nederland', 'Netherlands', 'Kingdom of the Netherlands', '네덜란드'],
  ['NC', 'Nouvelle-Calédonie', 'New Caledonia', 'New Caledonia', '누벨칼레도니'],
  ['NZ', 'Aotearoa', 'New Zealand', 'New Zealand', '뉴질랜드'],
  ['NI', 'Nicaragua', 'Nicaragua', 'Republic of Nicaragua', '니카라과'],
  ['NE', 'Niger', 'Niger', 'Republic of Niger', '니제르'],
  ['NG', 'Nigeria', 'Nigeria', 'Federal Republic of Nigeria', '나이지리아'],
  ['NU', 'Niuē', 'Niue', 'Niue', '니우에'],
  ['NF', "Norf'k Ailen", 'Norfolk Island', 'Territory of Norfolk Island', '노퍽 섬'],
  ['KP', '조선', 'North Korea', "Democratic People's Republic of Korea", '조선'],
  ['MK', 'Македонија', 'North Macedonia', 'Republic of North Macedonia', '북마케도니아'],
  [
    'MP',
    'Northern Mariana Islands',
    'Northern Mariana Islands',
    'Commonwealth of the Northern Mariana Islands',
    '북마리아나 제도',
  ],
  ['NO', 'Noreg', 'Norway', 'Kingdom of Norway', '노르웨이'],
  ['OM', 'عمان', 'Oman', 'Sultanate of Oman', '오만'],
  ['PK', 'پاكستان', 'Pakistan', 'Islamic Republic of Pakistan', '파키스탄'],
  ['PW', 'Belau', 'Palau', 'Republic of Palau', '팔라우'],
  ['PS', 'فلسطين', 'Palestine', 'State of Palestine', '팔레스타인'],
  ['PA', 'Panamá', 'Panama', 'Republic of Panama', '파나마'],
  [
    'PG',
    'Papua Niu Gini',
    'Papua New Guinea',
    'Independent State of Papua New Guinea',
    '파푸아뉴기니',
  ],
  ['PY', 'Paraguái', 'Paraguay', 'Republic of Paraguay', '파라과이'],
  ['PE', 'Piruw', 'Peru', 'Republic of Peru', '페루'],
  ['PH', 'Pilipinas', 'Philippines', 'Republic of the Philippines', '필리핀'],
  ['PN', 'Pitcairn Islands', 'Pitcairn Islands', 'Pitcairn Group of Islands', '핏케언 제도'],
  ['PL', 'Polska', 'Poland', 'Republic of Poland', '폴란드'],
  ['PT', 'Portugal', 'Portugal', 'Portuguese Republic', '포르투갈'],
  ['PR', 'Puerto Rico', 'Puerto Rico', 'Commonwealth of Puerto Rico', '푸에르토리코'],
  ['QA', 'قطر', 'Qatar', 'State of Qatar', '카타르'],
  ['CG', 'République du Congo', 'Republic of the Congo', 'Republic of the Congo', '콩고'],
  ['RE', 'La Réunion', 'Réunion', 'Réunion Island', '레위니옹'],
  ['RO', 'România', 'Romania', 'Romania', '루마니아'],
  ['RU', 'Россия', 'Russia', 'Russian Federation', '러시아'],
  ['RW', 'Rwanda', 'Rwanda', 'Republic of Rwanda', '르완다'],
  [
    'BL',
    'Saint-Barthélemy',
    'Saint Barthélemy',
    'Collectivity of Saint Barthélemy',
    '생바르텔레미',
  ],
  [
    'SH',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Helena, Ascension and Tristan da Cunha',
    '세인트헬레나',
  ],
  [
    'KN',
    'Saint Kitts and Nevis',
    'Saint Kitts and Nevis',
    'Federation of Saint Christopher and Nevis',
    '세인트키츠 네비스',
  ],
  ['LC', 'Saint Lucia', 'Saint Lucia', 'Saint Lucia', '세인트루시아'],
  ['MF', 'Saint-Martin', 'Saint Martin', 'Saint Martin', '생마르탱'],
  [
    'PM',
    'Saint-Pierre-et-Miquelon',
    'Saint Pierre and Miquelon',
    'Saint Pierre and Miquelon',
    '생피에르 미클롱',
  ],
  [
    'VC',
    'Saint Vincent and the Grenadines',
    'Saint Vincent and the Grenadines',
    'Saint Vincent and the Grenadines',
    '세인트빈센트 그레나딘',
  ],
  ['WS', 'Sāmoa', 'Samoa', 'Independent State of Samoa', '사모아'],
  ['SM', 'San Marino', 'San Marino', 'Most Serene Republic of San Marino', '산마리노'],
  [
    'ST',
    'São Tomé e Príncipe',
    'São Tomé and Príncipe',
    'Democratic Republic of São Tomé and Príncipe',
    '상투메 프린시페',
  ],
  ['SA', 'السعودية', 'Saudi Arabia', 'Kingdom of Saudi Arabia', '사우디아라비아'],
  ['SN', 'Sénégal', 'Senegal', 'Republic of Senegal', '세네갈'],
  ['RS', 'Србија', 'Serbia', 'Republic of Serbia', '세르비아'],
  ['SC', 'Sesel', 'Seychelles', 'Republic of Seychelles', '세이셸'],
  ['SL', 'Sierra Leone', 'Sierra Leone', 'Republic of Sierra Leone', '시에라리온'],
  ['SG', 'Singapura', 'Singapore', 'Republic of Singapore', '싱가포르'],
  ['SX', 'Saint-Martin', 'Sint Maarten', 'Sint Maarten', '신트마르턴'],
  ['SK', 'Slovensko', 'Slovakia', 'Slovak Republic', '슬로바키아'],
  ['SI', 'Slovenija', 'Slovenia', 'Republic of Slovenia', '슬로베니아'],
  ['SB', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands', '솔로몬 제도'],
  ['SO', 'الصومال', 'Somalia', 'Federal Republic of Somalia', '소말리아'],
  ['ZA', 'South Africa', 'South Africa', 'Republic of South Africa', '남아프리카'],
  [
    'GS',
    'South Georgia',
    'South Georgia',
    'South Georgia and the South Sandwich Islands',
    '조지아',
  ],
  ['SS', 'South Sudan', 'South Sudan', 'Republic of South Sudan', '남수단'],
  ['ES', 'España', 'Spain', 'Kingdom of Spain', '스페인'],
  ['LK', 'ශ්‍රී ලංකාව', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', '스리랑카'],
  ['SD', 'السودان', 'Sudan', 'Republic of the Sudan', '수단'],
  ['SR', 'Suriname', 'Suriname', 'Republic of Suriname', '수리남'],
  [
    'SJ',
    'Svalbard og Jan Mayen',
    'Svalbard and Jan Mayen',
    'Svalbard og Jan Mayen',
    '스발바르 얀마옌 제도',
  ],
  ['SE', 'Sverige', 'Sweden', 'Kingdom of Sweden', '스웨덴'],
  ['CH', 'Suisse', 'Switzerland', 'Swiss Confederation', '스위스'],
  ['SY', 'سوريا', 'Syria', 'Syrian Arab Republic', '시리아'],
  ['TW', '台灣', 'Taiwan', 'Republic of China (Taiwan)', '대만'],
  ['TJ', 'Таджикистан', 'Tajikistan', 'Republic of Tajikistan', '타지키스탄'],
  ['TZ', 'Tanzania', 'Tanzania', 'United Republic of Tanzania', '탄자니아'],
  ['TH', 'ประเทศไทย', 'Thailand', 'Kingdom of Thailand', '태국'],
  ['TL', 'Timor-Leste', 'Timor-Leste', 'Democratic Republic of Timor-Leste', '동티모르'],
  ['TG', 'Togo', 'Togo', 'Togolese Republic', '토고'],
  ['TK', 'Tokelau', 'Tokelau', 'Tokelau', '토켈라우'],
  ['TO', 'Tonga', 'Tonga', 'Kingdom of Tonga', '통가'],
  [
    'TT',
    'Trinidad and Tobago',
    'Trinidad and Tobago',
    'Republic of Trinidad and Tobago',
    '트리니다드 토바고',
  ],
  ['TN', 'تونس', 'Tunisia', 'Tunisian Republic', '튀니지'],
  ['TR', 'Türkiye', 'Türkiye', 'Republic of Türkiye', '터키'],
  ['TM', 'Туркмения', 'Turkmenistan', 'Turkmenistan', '투르크메니스탄'],
  [
    'TC',
    'Turks and Caicos Islands',
    'Turks and Caicos Islands',
    'Turks and Caicos Islands',
    '터크스 케이커스 제도',
  ],
  ['TV', 'Tuvalu', 'Tuvalu', 'Tuvalu', '투발루'],
  ['UG', 'Uganda', 'Uganda', 'Republic of Uganda', '우간다'],
  ['UA', 'Україна', 'Ukraine', 'Ukraine', '우크라이나'],
  ['AE', 'الإمارات', 'United Arab Emirates', 'United Arab Emirates', '아랍에미리트'],
  [
    'GB',
    'United Kingdom',
    'United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland',
    '영국',
  ],
  ['US', 'United States', 'United States', 'United States of America', '미국'],
  [
    'UM',
    'United States Minor Outlying Islands',
    'United States Minor Outlying Islands',
    'United States Minor Outlying Islands',
    '미국령 군소 제도',
  ],
  [
    'VI',
    'United States Virgin Islands',
    'United States Virgin Islands',
    'Virgin Islands of the United States',
    '미국령 버진아일랜드',
  ],
  ['UY', 'Uruguay', 'Uruguay', 'Oriental Republic of Uruguay', '우루과이'],
  ['UZ', 'Узбекистан', 'Uzbekistan', 'Republic of Uzbekistan', '우즈베키스탄'],
  ['VU', 'Vanuatu', 'Vanuatu', 'Republic of Vanuatu', '바누아투'],
  ['VA', 'Vaticano', 'Vatican City', 'Vatican City State', '바티칸'],
  ['VE', 'Venezuela', 'Venezuela', 'Bolivarian Republic of Venezuela', '베네수엘라'],
  ['VN', 'Việt Nam', 'Vietnam', 'Socialist Republic of Vietnam', '베트남'],
  [
    'WF',
    'Wallis et Futuna',
    'Wallis and Futuna',
    'Territory of the Wallis and Futuna Islands',
    '왈리스 퓌튀나',
  ],
  ['EH', 'Western Sahara', 'Western Sahara', 'Sahrawi Arab Democratic Republic', '서사하라'],
  ['YE', 'اليمن', 'Yemen', 'Republic of Yemen', '예멘'],
  ['ZM', 'Zambia', 'Zambia', 'Republic of Zambia', '잠비아'],
  ['ZW', 'Zimbabwe', 'Zimbabwe', 'Republic of Zimbabwe', '짐바브웨'],
]

export const countryOptions = Object.freeze(
  countryRecords.map(([code, nativeName, englishName, apiValue, koreanName]) =>
    Object.freeze({ code, nativeName, englishName, apiValue, koreanName }),
  ),
)

const countryOptionByCode = new Map(countryOptions.map((country) => [country.code, country]))

export function getCountryOption(code) {
  return countryOptionByCode.get(code?.toUpperCase()) ?? null
}
